---
- name: Install Nginx
  hosts: "{{ custom_host }}"
  become: yes

  tasks:
  - name: Install Nginx packages
    ansible.builtin.apt:
      name: nginx
      state: present 

  - name: Start Nginx service
    ansible.builtin.service:
      name: nginx
      state: started

  - name: Enable Nginx service
    ansible.builtin.service:
      name: nginx
      enabled: yes

  - name: Allow 80/443 tcp
    ansible.builtin.shell:
      cmd: ufw allow 80/tcp ; ufw allow 443/tcp

  - name: Reload UFW
    ansible.builtin.shell:
      cmd: yes | ufw reload

