---
- name: Reboot
  hosts: "{{ custom_host }}"
  become: yes
  tasks:
    - name: Reboot hosts
      ansible.builtin.reboot:
    
    - name: Sleep
      ansible.builtin.pause:
        minutes: 1

    - name: Ping check
      ansible.builtin.ping:

